name = "roll-doradogame-casino"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-doradogame.casino"
HMAC_KEY = "9c5c327df463425d6638155915011eca61dddff601eca316d4c121c8da703bf9"
COOKIE_NAME = "pb0"
PLAY_PATH = "begin"
BUTTON_ID = "p9527eaf0b1fe993e13c39557c2eb8644"
GATE_SALT = "72eb3a150867bfdd"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "gam1"
CTA_SELECTOR = ".play-button"
